const ChatsActionTypes = {
  GET_ALL_USER_CHATS_START: 'GET_ALL_USER_CHATS_START',
  GET_ALL_USER_CHATS_SUCCESS: 'GET_ALL_USER_CHATS_SUCCESS',
  GET_ALL_USER_CHATS_FAILURE: 'GET_ALL_USER_CHATS_FAILURE',

  GET_CHAT_ID_START: 'GET_CHAT_ID_START',
  GET_CHAT_ID_SUCCESS: 'GET_CHAT_ID_SUCCESS',
  GET_CHAT_ID_FAILURE: 'GET_CHAT_ID_FAILURE',

  GET_CHAT_BY_ID_START: 'GET_CHAT_BY_ID_START',
  GET_CHAT_BY_ID_SUCCESS: 'GET_CHAT_BY_ID_SUCCESS',
  GET_CHAT_BY_ID_FAILURE: 'GET_CHAT_BY_ID_FAILURE',

  CREATE_GROUP_START: 'CREATE_GROUP_START',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_FAILURE: 'CREATE_GROUP_FAILURE',

  UPDATE_GROUP_INFO_START: 'UPDATE_GROUP_INFO_START',
  UPDATE_GROUP_INFO_SUCCESS: 'UPDATE_GROUP_INFO_SUCCESS',
  UPDATE_GROUP_INFO_FAILURE: 'UPDATE_GROUP_INFO_FAILURE',

  DELETE_CHAT_START: 'DELETE_CHAT_START',
  DELETE_CHAT_SUCCESS: 'DELETE_CHAT_SUCCESS',
  DELETE_CHAT_FAILURE: 'DELETE_CHAT_FAILURE',

  REMOVE_USER_FROM_CHAT_START: 'REMOVE_USER_FROM_CHAT_START',
  REMOVE_USER_FROM_CHAT_SUCCESS: 'REMOVE_USER_FROM_CHAT_SUCCESS',
  REMOVE_USER_FROM_CHAT_FAILURE: 'REMOVE_USER_FROM_CHAT_FAILURE',

  UPLOAD_MESSAGE_IMAGE_START: 'UPLOAD_MESSAGE_IMAGE_START',
  UPLOAD_MESSAGE_IMAGE_SUCCESS: 'UPLOAD_MESSAGE_IMAGE_SUCCESS',
  UPLOAD_MESSAGE_IMAGE_FAILURE: 'UPLOAD_MESSAGE_IMAGE_FAILURE'
};

export default ChatsActionTypes;
