const ChatsActionTypes = {
  GET_ALL_USER_CHATS_START: 'GET_ALL_USER_CHATS_START',
  GET_ALL_USER_CHATS_SUCCESS: 'GET_ALL_USER_CHATS_SUCCESS',
  GET_ALL_USER_CHATS_FAILURE: 'GET_ALL_USER_CHATS_FAILURE',

  GET_CHAT_BY_ID_START: 'GET_CHAT_BY_ID_START',
  GET_CHAT_BY_ID_SUCCESS: 'GET_CHAT_BY_ID_SUCCESS',
  GET_CHAT_BY_ID_FAILURE: 'GET_CHAT_BY_ID_FAILURE',

  GET_CHAT_BY_OPPONENT_ID_START: 'GET_CHAT_BY_OPPONENT_ID_START',
  GET_CHAT_BY_OPPONENT_ID_SUCCESS: 'GET_CHAT_BY_OPPONENT_ID_SUCCESS',
  GET_CHAT_BY_OPPONENT_ID_FAILURE: 'GET_CHAT_BY_OPPONENT_ID_FAILURE'
};

export default ChatsActionTypes;
