const ChatsActionTypes = {
  GET_ALL_USER_CHATS_START: 'GET_ALL_USER_CHATS_START',
  GET_ALL_USER_CHATS_SUCCESS: 'GET_ALL_USER_CHATS_SUCCESS',
  GET_ALL_USER_CHATS_FAILURE: 'GET_ALL_USER_CHATS_FAILURE',

  GET_CHAT_ID_START: 'GET_CHAT_ID_START',
  GET_CHAT_ID_SUCCESS: 'GET_CHAT_ID_SUCCESS',
  GET_CHAT_ID_FAILURE: 'GET_CHAT_ID_FAILURE',

  CREATE_GROUP_START: 'CREATE_GROUP_START',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_FAILURE: 'CREATE_GROUP_FAILURE'
};

export default ChatsActionTypes;
