const CurrentUserActionTypes = {
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
  SIGN_UP_USER_FAILURE: 'SIGN_UP_USER_FAILURE',

  SIGN_IN_USER_START: 'SIGN_IN_USER_START',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',

  SIGN_IN_WITH_FACEBOOK_START: 'SIGN_IN_WITH_FACEBOOK_START',
  SIGN_IN_WITH_FACEBOOK_SUCCESS: 'SIGN_IN_WITH_FACEBOOK_SUCCESS',
  SIGN_IN_WITH_FACEBOOK_FAILURE: 'SIGN_IN_WITH_FACEBOOK_FAILURE',

  SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
  SIGN_IN_WITH_GOOGLE_SUCCESS: 'SIGN_IN_WITH_GOOGLE_SUCCESS',
  SIGN_IN_WITH_GOOGLE_FAILURE: 'SIGN_IN_WITH_GOOGLE_FAILURE',

  UPDATE_USER_AVATAR_START: 'UPDATE_USER_AVATAR_START',
  UPDATE_USER_AVATAR_SUCCESS: 'UPDATE_USER_AVATAR_SUCCESS',
  UPDATE_USER_AVATAR_FAILURE: 'UPDATE_USER_AVATAR_FAILURE',

  UPDATE_USER_INFO_START: 'UPDATE_USER_INFO_START',
  UPDATE_USER_INFO_SUCCESS: 'UPDATE_USER_INFO_SUCCESS',
  UPDATE_USER_INFO_FAILURE: 'UPDATE_USER_INFO_FAILURE',

  UPDATE_USER_NOTIFICATION_TOKEN_START: 'UPDATE_USER_NOTIFICATION_TOKEN_START',
  UPDATE_USER_NOTIFICATION_TOKEN_SUCCESS:
    'UPDATE_USER_NOTIFICATION_TOKEN_SUCCESS',
  UPDATE_USER_NOTIFICATION_TOKEN_FAILURE:
    'UPDATE_USER_NOTIFICATION_TOKEN_FAILURE',

  LOADING_USER_START: 'LOADING_USER_START',
  LOADING_USER_SUCCESS: 'LOADING_USER_SUCCESS',
  LOADING_USER_FAILURE: 'LOADING_USER_FAILURE',

  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_OUT_USER_FAILURE: 'SIGN_OUT_USER_FAILURE',

  CHANGE_USER_PASSWORD_START: 'CHANGE_USER_PASSWORD_START',
  CHANGE_USER_PASSWORD_SUCCESS: 'CHANGE_USER_PASSWORD_SUCCESS',
  CHANGE_USER_PASSWORD_FAILURE: 'CHANGE_USER_PASSWORD_FAILURE',

  FORGET_USER_PASSWORD_START: 'FORGET_USER_PASSWORD_START',
  FORGET_USER_PASSWORD_SUCCESS: 'FORGET_USER_PASSWORD_SUCCESS',
  FORGET_USER_PASSWORD_FAILURE: 'FORGET_USER_PASSWORD_FAILURE',

  CONTACT_US_START: 'CONTACT_US_START',
  CONTACT_US_SUCCESS: 'CONTACT_US_SUCCESS',
  CONTACT_US_FAILURE: 'CONTACT_US_FAILURE',

  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILURE: 'DELETE_USER_FAILURE'
};

export default CurrentUserActionTypes;
